framework:
    translator: { fallback: %locale% }

fos_user:
    db_driver: orm
    firewall_name: admin_panel
    user_class: Resumin\Bundle\ManagerBundle\Entity\User
    registration:
      confirmation:
        enabled: true
