resumin_admin:
    resource: "@ResuminAdminBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@FSiAdminBundle/Resources/config/routing/admin.yml"
    prefix: /manager

admin_security:
    resource: "@FSiAdminSecurityBundle/Resources/config/routing/admin_security.yml"
    prefix: /manager

admin_translatable:
    resource: "@FSiAdminTranslatableBundle/Resources/config/routing/admin.yml"
    prefix: /manager

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /manager/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /manager/resetting
