security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_panel:
            pattern: ^/manager
            form_login:
                check_path: /manager/login_check
                login_path: /manager/login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /manager
                remember_me: true
            logout:
                path:  /manager/logout
            anonymous: true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /
                domain:   ~

    access_control:
        - { path: ^/manager/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manager/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manager/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manager, roles: ROLE_USER }
