security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_panel:
            pattern: ^/manager
            form_login:
                provider: fos_userbundle
                check_path: fsi_admin_security_user_check
                login_path: fsi_admin_security_user_login
                default_target_path: /manager
                always_use_default_target_path: true
            logout:
                path: fsi_admin_security_user_logout
            anonymous: ~

    access_control:
        - { path: ^/manager/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manager/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manager/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manager, roles: ROLE_USER }
